### ISSUE TITLE
Opportunity to capitalize on interactivity to showcase GatherLens?

### ISSUE THREAD

**Issue by mjskay** [journalovi/2023-park-gatherplots#13]
(I am not filling out a full review, and @nickelm please take this as you would a passing suggestion --- i.e. not with the weight of me wearing my journal editor hat, so ignoring it has no bearing on the outcome of your paper)

It is awesome to see you taking some advantage of interactivity in this paper already. It occurred to me that it would be very cool if the [GatherLens section](https://www.journalovi.org/2023-park-gatherplots/#gatherlens-a-gathering-magic-lens) had a working demo of GatherLens embedded in it, rather than a screenshot. Something you could do with this format that would not work in other formats :)

**Comment by nickelm** [comment]
This is a good point. However, my own implementation does not have a GatherLens feature. Based on reviewer feedback, I actually dropped the GatherLens bit from the new revision... Sorry. ;)

**Comment by mjskay** [comment]
Makes sense! alas :)
