### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by codementum** [journalovi/2023-park-gatherplots#6]
@domoritz 

@mjskay Asked me to create this issue to ping you to do an accessibility review of this paper. As part of this issue, it might be helpful to log your process in a checklist, which we can use to create an issue template in the style of the [initial editor checklist](https://github.com/journalovi/2023-park-gatherplots/issues/new?assignees=&labels=pre-review&projects=&template=initial-editor-checklist.md&title=Initial+Editor+Checklist).

If possible, it would be helpful to have this in the next six weeks, to align with the overall review timeline.
Thanks!

**Comment by domoritz** [comment]
Absolutely. I think it's great to have an example to go through as I create the checklist. Is it okay if I make the checklist in a GitHub issue for now (easier to edit) and then copy it into an issue template later?

**Comment by mjskay** [comment]
Thanks @domoritz!

> Is it okay if I make the checklist in a GitHub issue for now (easier to edit) and then copy it into an issue template later?

Yup that's perfect! That's how we created the editor checklist.

**Comment by domoritz** [comment]
Done in #10

**Comment by mjskay** [comment]
@codementum @domoritz since the accessibility review has now been done in a separate issue, can we close this?

**Comment by domoritz** [comment]
Yes. I cannot close issues in this repo so go for it.

**Comment by mjskay** [comment]
thanks!
